
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kausgroup.kaus.domain
  resources:
  - kauscrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kausgroup.kaus.domain
  resources:
  - kauscrds/status
  verbs:
  - get
  - patch
  - update
